### ISSUE TITLE
cli tools?

### ISSUE THREAD

**Issue by zvezdochiot** [phma/bezitopo#10]
It makes sense to have cli utilities (without Qt). Namely:
```sh
tintops [options] you.asc out.ps
sitetops [options] you.asc out.ps
```
(alternative to viewers, in many cases more useful).

PS: If a design with [options] seems cumbersome, there is always an option to use configuration files.

**Comment by phma** [comment]
What would they do? What is a .site file? Would it make more sense to read a Bezitopo file (*.bez), which Bezitopo can't read yet?

I'm guessing that you.asc is like the topo0.asc file on bezitopo.org and in the repo. That is a CSV file, a list of points, which has the .asc extension because of whatever my surveying teacher was doing at the time. It is not a TIN and does not include breaklines; the breaklines I added later, as a separate file, though some of them were impossible (the points were collected by a class of students and some of us, including me, did not know the correct procedure to collect points at the top and bottom of a curved wall so that breaklines could be drawn).

**Comment by zvezdochiot** [comment]
Hmm. I put it badly. Utilities for generating PostScript without using the GUI are offered, as in `bezitest` (generation is controlled by either [options] or the configuration file).

**Comment by phma** [comment]
Bezitest is the test program. It produces lots of PostScript files so that I can see what's going on. When I was writing the TIN generation tests, for instance, I could see a bad TIN a lot easier than I could tell the computer to tell that a TIN was bad. Bezitest checks the total length of TIN edges, but the only way I could calculate that number was to generate a TIN, output the TIN in PS and the total length, and look at the TIN.

**Comment by zvezdochiot** [comment]
no actual
